
services:

  client:
      build:
        context: Frontend/
        dockerfile: Dockerfile
      container_name: frontend_app
      ports:
        - "3000:3000"

  server:
    build:
      context: src/server/
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_PORT=${DJANGO_DB_PORT}
      - DJANGO_TOKEN_KEY=${DJANGO_TOKEN_KEY}

volumes:
  postgres_data: {}
  pgadmin_data: {}
