# Generated by Django 5.1.1 on 2024-10-19 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_reservations_rooms'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesCashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypesTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy', models.JSONField()),
                ('count_accompany', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('date_finish', models.DateTimeField()),
                ('status', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('id_guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.reservations')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_reservations', to='inventory.rooms')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reservations', to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type_cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.typescashregister')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('value', models.IntegerField()),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.cashregister')),
                ('type_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.typestransactions')),
            ],
        ),
    ]
