apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend-app
spec:
  containers:
  - name: backend-container
    image: cristiank/corona-real-backend:1.2
    ports:
    - containerPort: 4800
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-app
  ports:
  - protocol: TCP
    port: 4800
    targetPort: 80
  type: NodePort