# Generated by Django 5.1.1 on 2024-10-19 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_reservations_rooms'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproducts',
            name='transaction_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.transactions'),
        ),
    ]
