# Generated by Django 5.1.1 on 2024-10-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rooms_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='name',
        ),
    ]
