# Generated by Django 5.1.1 on 2024-11-17 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_products_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="inv",
        ),
    ]
