# Generated by Django 5.1.1 on 2024-11-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_remove_products_inv"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="type_product",
        ),
        migrations.DeleteModel(
            name="TypesProducts",
        ),
    ]
